name: Formatting with pre-commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v6
    - name: Check code format with pre-commit
      uses: pre-commit/action@v3.0.1
